mensaje
jfelipeq14/hermes-react pull request #52
Opened 2024-09-02 02:48 UTC by Goez905

Login listo, botones de registrar organizados y se empezó localstore

2024-09-02 03:06 UTC, jfelipeq14 requested changes

2024-09-02 03:06 UTC, jfelipeq14 commented on src/pages/role/permisos.jsx
No sé para qué se agregaron los espacios. Recomiendo usar prettier para formatear el codigo: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

2024-09-04 21:38 UTC, Goez905 commented on src/pages/home/auth/Register.jsx
> +  const handleSubmit = async (e) => {
okey

2024-09-04 21:38 UTC, Goez905 commented on src/pages/role/permisos.jsx
okey

2024-09-04 21:55 UTC, merged